### ISSUE TITLE
How to enable auto tag for react fragments?

### ISSUE THREAD

**Issue by AlejandroSanchez90** [windwp/nvim-ts-autotag#199] opened 2024-06-22 21:49 UTC
it possible to make this work for fragments swell? 

<> => </>

**Comment by roycrippen4** [comment] 2024-07-14 16:38
Just to clarify, you want version 1?

| = cursor position

Version 1

    Old text   Command   New text
       <|         >       <>|</>

---

Version 2

    Old text   Command   New text
       <|         >        </>

**Comment by PriceHiller** [comment] 2024-07-14 19:49
Should/will be closed by #202 

(Thanks to @roycrippen4 for the hard work 😄)

Duplicate of #185. Since there's discussion on-going here, I'll leave this open as well and close it alongside #185.

**Comment by roycrippen4** [comment] 2024-07-14 21:07
@PriceHiller Unfortunately it's not a duplicate of #185. It's a similar-ish problem, but #202 doesn't solve this. I'll be submitting a separate PR for this issue.

**Comment by AlejandroSanchez90** [comment] 2024-07-14 21:09
> @AlejandroSanchez90, for clarification, you want version 1?
> 
> | = cursor position
> 
> Version 1
> 
>     Old text   Command   New text
>        <|         >       <>|</>
> 
> ---
> 
> Version 2
> 
>     Old text   Command   New text
>        <|         >        </>
> 

Hi thanks for the reply, I was referring to version one

**Comment by roycrippen4** [comment] 2024-07-14 21:11
Sounds good, @AlejandroSanchez90. A PR has been submitted that fixes this issue and should be merged in shortly.

**Closed** 2024-07-14 21:39 UTC

**Comment by hanumanman** [comment] 2024-10-05 14:25
@roycrippen4 Thanks a lot for this feature! This works now when typing normally, but doesnt work when updating tag name using diw/ciw and the like
Example: <div></div> 
Delete div with diw => the text is now <></div> instead of <></>
