### ISSUE TITLE
React Typescript - Freezes Neovim after opening a generic of a function

### ISSUE THREAD

**Issue by AndreRojasMartinsson** [windwp/nvim-ts-autotag#222] opened 2024-11-27 08:08 UTC
Hey,
I'm currently facing a very big issue with autotag.
Whenever I wish to use a generic on a function I type the opening angled bracket (<) but as soon as I do that
the entire terminal freezes.

I narrowed it down to this extension when I tried removing it and attempting it again. If I try to type generic type parameters for a function it completely freezes until I close the tmux window and reopen it.

**Comment by PriceHiller** [comment] 2024-11-30 20:27
We had a PR merged (#199) for react fragment support that may be causing this. Almost certainly related to that.

**Comment by pnwatin** [comment] 2024-12-01 19:12
i think i've found the issue !

it's in `lua/nvim-ts-autotag/internal.lua` in the function `is_in_template_tag` line 37. There is a potential infinite loop (that triggers in case above)

here a fix that worked locally

```lua
local function is_in_template_tag()
    local cursor_node = utils.get_node_at_cursor()
    if not cursor_node then
        return false
    end

    local has_element = false
    local has_template_string = false

    local current_node = cursor_node
    local visited_nodes = {}

    while not (has_element and has_template_string) and current_node do
        local node_id = current_node:id()
        if visited_nodes[node_id] then
            -- Cycle detected, break the loop
            break
        end
        visited_nodes[node_id] = true

        if not has_element and current_node:type() == "element" then
            has_element = true
        end
        if not has_template_string and current_node:type() == "template_string" then
            has_template_string = true
        end
        current_node = current_node:parent() 
      
    end

    return has_element and has_template_string
end
```
Its seems that `current_node:parent()` might not return nil when he has no parent and because of this the loop keeps running and running, freezing neovim.
Not sure about this explanation since i'm not really familiar with lua nor treesitter.
What's your opinion @PriceHiller ?

i'll create a PR tomorrow.

**Comment by PriceHiller** [comment] 2024-12-02 01:32
>  What's your opinion @PriceHiller ?

I think the solution is fine with a 

What I'm not quite sure about is:

> Its seems that current_node:parent() might not return nil when he has no parent 

1. As in the `TSNode:parent()` is returning a child or just the current node? I'm not sure how calling `TSNode:parent()` ends up returning a duplicate node.

If it doesn't return `nil`, I noticed it may also return a empty table, another thing we *should* check for. I wonder if we're issuing a `:parent()` call on the empty table, leading to an error which then leads to a cascade somewhow.

2. Can you provide me with a recording? I just had some time in the last hour to check this out and I am having difficulties replicating locally.
  
Here's what I'm doing:

https://github.com/user-attachments/assets/89580b15-0c3d-498d-99e7-9c25a121313b


3. What version of Neovim are you running? `0.10.x`? I'm on nightly.
4. Have you tried updating the treesitter parsers (e.g. `TSUpdate typescript tsx`)?

I'm sure the bug is *real*, I just can't trigger it.

---

*Just a quick note, I won't be a pain here and block a bugfix that solves the issue in a short time frame, but I will need to investigate what's going on later. I'll gladly accept a PR for this in the short term.*

**Comment by pnwatin** [comment] 2024-12-02 11:17
```bash
$ nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1732813678
Run "nvim -V1 -v" for more info
``` 

my treesitter parser are all up to date. 

here's a basic reproduction in a `test.tsx` file :
https://github.com/user-attachments/assets/2416579d-f91f-4fb8-82c1-d37169ea4154

a more realistic reproduction in a nextjs project in a react component file:
https://github.com/user-attachments/assets/efd40340-3ae7-4cc4-84a5-1861f2d99ef5

Regarding the debug that i went throught on my local version of the plugin  i updated the loop to print current_node `id` and `type`. 
For the working `<></>` i get the following :

```
11:59:09 msg_show loop count 1
11:59:09 msg_show node id @Q<a4>^C^@`^@^@
11:59:09 msg_show node type jsx_opening_element
11:59:09 msg_show loop count 2
11:59:09 msg_show node id @Q<a4>^C^@`^@^@
11:59:09 msg_show node type jsx_opening_element
11:59:09 msg_show loop count 3
11:59:09 msg_show node id @Q<a4>^C^@`^@^@
11:59:09 msg_show node type jsx_opening_element

```

but for the bug i get this 
```
11:59:47 msg_show loop count 1
11:59:47 msg_show node id `<fc><a4>^C^@`^@^@
11:59:47 msg_show node type type_identifier
11:59:47 msg_show loop count 2
11:59:47 msg_show node id `<fc><a4>^C^@`^@^@
11:59:47 msg_show node type type_identifier
11:59:47 msg_show Visiting an already visited node. Exiting the loop
```

i don't know if this helps you @PriceHiller 
anyway thank you for your time. This bug really annoys me haha.

**Closed** 2024-12-02 18:31 UTC
